--BOM(Bill of Material)이란?
--하나의 완제품이 만들어지는데 필요한 구성품목들의 내역 혹은 조합도를 말함

CREATE TABLE BOM(
    ITEM_ID NUMBER,
    PARENT_ID NUMBER,
    ITEM_NAME VARCHAR2(150),
    ITEM_QTY NUMBER,
    CONSTRAINT PK_BOM PRIMARY KEY(ITEM_ID)
);

COMMENT ON TABLE BOM IS '컴퓨터 구성 정보';
COMMENT ON COLUMN BOM.ITEM_ID IS '품목 식별자';
COMMENT ON COLUMN BOM.PARENT_ID IS '상위 품목 식별자';
COMMENT ON COLUMN BOM.ITEM_NAME IS '품목 이름';
COMMENT ON COLUMN BOM.ITEM_QTY IS '품목 개수';

INSERT INTO BOM VALUES ( 1001, NULL, '컴퓨터', 1);
INSERT INTO BOM VALUES ( 1002, 1001, '본체', 1);
INSERT INTO BOM VALUES ( 1003, 1001, '모니터', 1);
INSERT INTO BOM VALUES ( 1004, 1001, '프린터', 1);

INSERT INTO BOM VALUES ( 1005, 1002, '메인보드', 1);
INSERT INTO BOM VALUES ( 1006, 1002, '랜카드', 1);
INSERT INTO BOM VALUES ( 1007, 1002, '파워서플라이', 1);
INSERT INTO BOM VALUES ( 1008, 1005, 'CPU', 1);
INSERT INTO BOM VALUES ( 1009, 1005, 'RAM', 1);
INSERT INTO BOM VALUES ( 1010, 1005, '그래픽카드', 1);
INSERT INTO BOM VALUES ( 1011, 1005, '기타장치', 1);

COMMIT;


---
SELECT ITEM_NAME
     , ITEM_ID
     , PARENT_ID
FROM BOM
START WITH PARENT_ID IS NULL
CONNECT BY PRIOR ITEM_ID = PARENT_ID;

------
CREATE TABLE AMUMAL(
    NO NUMBER,
    TITLE VARCHAR2(90),
    WRITER VARCHAR2(60),
    PNO NUMBER,
    CONSTRAINT PK_AMUMAL PRIMARY KEY(NO)
);

INSERT INTO AMUMAL VALUES(1,'여름은 더워','홍길동',NULL);   
INSERT INTO AMUMAL VALUES(2,'맞아 더워','김철수',1);   
INSERT INTO AMUMAL VALUES(3,'그래서 여름이지','홍길동',1);   
INSERT INTO AMUMAL VALUES(4,'정말 그래','노홍철',3);   
INSERT INTO AMUMAL VALUES(5,'그래 정말','지상철',4);   
INSERT INTO AMUMAL VALUES(6,'말장난 하지마','노홍철',4);   
INSERT INTO AMUMAL VALUES(7,'말장난 좋은걸','지상철',4);   
INSERT INTO AMUMAL VALUES(8,'그러게','하정우',3);   
INSERT INTO AMUMAL VALUES(9,'가을아 와라','김진수',3);   
INSERT INTO AMUMAL VALUES(10,'그래도 여름이 좋아','박명수',1);   
COMMIT;

---
SELECT NO
        , LPAD('ㄴ' ,2*(LEVEL-1)) || TITLE AS TITLE
        , WRITER
        , PNO
FROM AMUMAL
START WITH PNO IS NULL
CONNECT BY PRIOR NO = PNO
ORDER SIBLINGS BY NO DESC  --- 계층형을 유지하면서 최신글이 위로 올라옴
;

CREATE TABLE
