SELECT COLUMN_NAME
, DATA_TYPE
, CASE WHEN DATA_TYPE='NUMBER' THEN 'private int ' || FN_GETCAMEL(COLUMN_NAME) || ';'
WHEN DATA_TYPE IN('VARCHAR2','CHAR') THEN 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
WHEN DATA_TYPE='DATE' THEN 'private Date ' || FN_GETCAMEL(COLUMN_NAME) || ';'
ELSE 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
END AS CAMEL_CASE
, '' RESULTMAP
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CART_DET';


INSERT INTO CART(CART_ID, NAME, SHIPPING_DATE, COUNTRY, ZIP_CODE, ADDRESS_NAME, ADDRESS_DETAIL, REGIST_DT);

CREATE TABLE ITEM(
    ITEM_ID NUMBER,
    ITEM_NAME VARCHAR2(150,
    PRICE NUMBER,
    DESCRIPTION VARCHAR2(300),
    PICTYURE_URL VARCHAR2(300),
    CONSTRAINT PK_ITEM PRIMARY KEY(ITEM_ID)
    );
COMMENT ON TABLE ITEM IS '첨부파일1';
COMMENT ON COLUMN ITEM.ITEM_ID IS '파일 아이디';
COMMENT ON COLUMN ITEM.ITEM_NAME IS '파일 명';
COMMENT ON COLUMN ITEM.PRICE IS '가격';
COMMENT ON COLUMN ITEM.DESCRIPTION IS '설명글';
COMMENT ON COLUMN ITEM.PICTYURE_URL IS '상품 이미지';


    
CREATE TABLE ITEM2(
    ITEM_ID NUMBER,
    ITEM_NAME VARCHAR2(150,
    PRICE NUMBER,
    DESCRIPTION VARCHAR2(300),
    PICTYURE_URL VARCHAR2(300),
    PICTYURE_URL2 VARCHAR2(300),
    CONSTRAINT PK_ITEM PRIMARY KEY(ITEM_ID)
    );
    
    -------------------
    CREATE TABLE ITEM(
    ITEM_ID NUMBER,
    ITEM_NAME VARCHAR2(150),
    PRICE NUMBER,
    DESCRIPTION VARCHAR2(300),
    PICTURE_URL VARCHAR2(300),
    CONSTRAINT PK_ITEM PRIMARY KEY(ITEM_ID)
);
COMMENT ON TABLE ITEM IS '상품1';
COMMENT ON COLUMN ITEM.ITEM_ID IS '상품 아이디';
COMMENT ON COLUMN ITEM.ITEM_NAME IS '상품 명';
COMMENT ON COLUMN ITEM.PRICE IS '가격';
COMMENT ON COLUMN ITEM.DESCRIPTION IS '설명';
COMMENT ON COLUMN ITEM.PICTURE_URL IS '상품 이미지';

--
    CREATE TABLE ITEM2(
    ITEM_ID NUMBER,
    ITEM_NAME VARCHAR2(150),
    PRICE NUMBER,
    DESCRIPTION VARCHAR2(300),
    PICTURE_URL VARCHAR2(300),
    PICTURE_URL2 VARCHAR2(300),
    CONSTRAINT PK_ITEM2 PRIMARY KEY(ITEM_ID)
    );
    
COMMENT ON TABLE ITEM2 IS '상품2';
COMMENT ON COLUMN ITEM2.ITEM_ID IS '상품 아이디';
COMMENT ON COLUMN ITEM2.ITEM_NAME IS '상품 명';
COMMENT ON COLUMN ITEM2.PRICE IS '가격';
COMMENT ON COLUMN ITEM2.DESCRIPTION IS '설명';
COMMENT ON COLUMN ITEM2.PICTURE_URL IS '상품 이미지1';
COMMENT ON COLUMN ITEM2.PICTURE_URL2 IS '상품 이미지2';

---
    CREATE TABLE ITEM3(
    ITEM_ID NUMBER,
    ITEM_NAME VARCHAR2(150),
    PRICE NUMBER,
    DESCRIPTION VARCHAR2(300),
    CONSTRAINT PK_ITEM3 PRIMARY KEY(ITEM_ID)
    );
--첨부파일   
CREATE TABLE ITEM_ATTACH(
    SEQ NUMBER,
    ITEM_ID NUMBER,
    FULLNAME VARCHAR2(300),
    REGDATE DATE,
    CONSTRAINT PK_ITEM_ATTACH PRIMARY KEY(SEQ)
);


--
--카멜표기법
SELECT COLUMN_NAME
, DATA_TYPE
, CASE WHEN DATA_TYPE='NUMBER' THEN 'private int ' || FN_GETCAMEL(COLUMN_NAME) || ';'
WHEN DATA_TYPE IN('VARCHAR2','CHAR') THEN 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
WHEN DATA_TYPE='DATE' THEN 'private Date ' || FN_GETCAMEL(COLUMN_NAME) || ';'
ELSE 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
END AS CAMEL_CASE
, '' RESULTMAP
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'ATTACH';


-----------
CREATE TABLE ATTACH(
    SEQ NUMBER,
    TID VARCHAR2(30),
    ATTACH_NAME VARCHAR2(300),
    ATTACH_SIZE NUMBER,
    ATTACH_TYPE VARCHAR2(30),
    REGIST_DATE DATE,
    CONSTRAINT PK_ATTACH PRIMARY KEY(SEQ)
);

-----
INSERT ALL
INTO ATTACH VALUES(1,'P1238','1',2,'jpeg',sysdate)
INTO ATTACH VALUES(2,'P1238','2',2,'jpeg',sysdate)
INTO ATTACH VALUES(3,'P1238','3',2,'jpeg',sysdate)

SELECT * FROM SYS.DUAL;

commit

---------------
ALTER TABLE ADDRESS
ADD (CONSTRAINT R_293 FOREIGN KEY (USER_ID) REFERENCES MEMBER(USER_ID));

--
INSERT INTO MEMBER (USER_ID, PASSWORD, COIN, BIRTH, GENDER, NATIONALITY, MARRIAGED, CARS, HOBBY_LIST)
VALUES('a001','java',100,'2022-11-01','male','korea','false','qm6,auid','movie,book');

INSERT INTO ADDRESS(USER_ID, POST_CODE, ADDRESS, ADDRESS_DETAIL)
VALUES('a001','12345','대전 중구 중아로 12','개똥이 빌딩');

INSERT INTO CARD(USER_ID, NO, VALID_MONTH)
VALUES('a001','12345','2022-11-01');
INSERT INTO CARD(USER_ID, NO, VALID_MONTH)
VALUES('a001','12346','2022-11-01');

COMMIT
