-- 첫번째 방법임 조인
SELECT P.PRODUCT_ID
     , P.PNAME
     , P.UNIT_PRICE
     , P.DESCRIPTION
     , P.MANUFACTURER
     , P.CATEGORY
     , P.UNIT_IN_STOCK
     , P.CONDITION
     , A.ATTACH_NAME FILENAME
FROM   PRODUCT P, ATTACH A
WHERE  P.PRODUCT_ID = A.TID(+)
AND    P.PRODUCT_ID = 'P4005'
AND    A.SEQ = 1;

-- 2번째 방법 서브쿼리
SELECT P.PRODUCT_ID
     , P.PNAME
     , P.UNIT_PRICE
     , P.DESCRIPTION
     , P.MANUFACTURER
     , P.CATEGORY
     , P.UNIT_IN_STOCK
     , P.CONDITION
     , (SELECT A.ATTACH_NAME FROM ATTACH A
        WHERE  P.PRODUCT_ID = A.TID
        AND    A.SEQ = 1) FILENAME
FROM   PRODUCT P
WHERE  P.PRODUCT_ID = 'P4005';

---
SELECT SUBSTR(MAX(PRODUCT_ID),0,1) 
     || TRIM(SUBSTR(MAX(PRODUCT_ID),2)+1)
FROM PRODUCT;


      
      
//

SELECT MEM_ID, MEM_NAME, MEM_JOB, MEM_LIKE
		FROM MEMBER
		WHERE 1=1