CREATE TABLE "CUSTOMER"(
"CUM_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE,
"CUM_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"CUM_JOB"  VARCHAR2(40 BYTE),
"CUM_LIKE" VARCHAR2(40 BYTE), 
"CUM_SKIL" VARCHAR2(40 BYTE),
CONSTRAINT "PK_CUM_ID" PRIMARY KEY ("CUM_ID") ENABLE
) ;

--- CUSTOMER INSERT
INSERT INTO CUSTOMER (CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL) VALUES ('a001','김은대','주부','수영','요리');
INSERT INTO CUSTOMER (CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL) VALUES ('a002','김대은','회사원','음악듣기','달리기');
INSERT INTO CUSTOMER (CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL) VALUES ('a003','이은대','장사꾼','영화보기','클라이밍');
INSERT INTO CUSTOMER (CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL) VALUES ('a004','이대은','공장장','게임','공부');
INSERT INTO CUSTOMER (CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL) VALUES ('a005','은대응','회사원','낚시','자전거타기');

COMMIT

--카멜표기법
SELECT COLUMN_NAME
, DATA_TYPE
, CASE WHEN DATA_TYPE='NUMBER' THEN 'private int ' || FN_GETCAMEL(COLUMN_NAME) || ';'
WHEN DATA_TYPE IN('VARCHAR2','CHAR') THEN 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
WHEN DATA_TYPE='DATE' THEN 'private Date ' || FN_GETCAMEL(COLUMN_NAME) || ';'
ELSE 'private String ' || FN_GETCAMEL(COLUMN_NAME) || ';'
END AS CAMEL_CASE
, '' RESULTMAP
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CUSTOMER';


--- CUSTOMER LIST
		SELECT CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL
		FROM CUSTOMER
		WHERE 1 = 1;
        
        
--- 리스트 페이지 부분 페이징 처리하기(ASC : 오름차순, DESC : 내림차순)
SELECT ROW_NUMBER() OVER (ORDER BY CUM_ID ASC),
CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL
FROM CUSTOMER 
ORDER BY CUM_ID ASC;   

------검색 부분 SQL
WITH T AS(
SELECT ROW_NUMBER() OVER (ORDER BY CUM_ID ASC),
    CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL
    FROM CUSTOMER
    WHERE 1=1
    AND (CUM_ID LIKE '%이%' 
    OR CUM_NAME LIKE '%이%'
    OR CUM_JOB LIKE '%이%'
    OR CUM_LIKE LIKE '%이%'
    OR CUM_SKIL LIKE '%이%')
)
SELECT * FROM T
WHERE T.RNUM BETWEEN 1*10 -9 AND 1 * 10;

SELECT * FROM CUSTOMER;
------ pc11 테이블 member 을 데이터를 옮기고 customer 로 옮김
insert into customer
SELECT mem_id, mem_name, mem_job, mem_like, mem_like FROM pc11.MEMBER
where mem_id > 'a001';

---total 만들기
SELECT COUNT(*) FROM CUSTOMER;


---- 테이블 sql 반복문으로 컬럼 늘리기
DECLARE
BEGIN
    FOR I IN 101..335 LOOP
        INSERT INTO CUSTOMER(CUM_ID,CUM_NAME,CUM_JOB,CUM_LIKE,CUM_SKIL)
        VALUES('z'||TRIM(TO_CHAR(I,'000')),'개똥이'||TRIM(TO_CHAR(I,'000')),'프로그래머','개발하기','음악감상');
    END LOOP;
    COMMIT;
END;
    
DELETE FROM CUSTOMER WHERE CUM_ID > 'z 001';
COMMIT;
TO_CHAR(2,'000') FROM DUAL;


------------11/03
SELECT COUNT(*) FROM CUSTOMER WHERE CUM_ID = 'abc001';

commit


---------- 상세보기 조인 원래테이블 + attach 테이블
SELECT C.CUM_ID, C.CUM_NAME, C.CUM_JOB, C.CUM_LIKE, C.CUM_SKIL,
        A.SEQ, A.TID, A.ATTACH_NAME
FROM CUSTOMER C LEFT OUTER JOIN ATTACH A ON (C.CUM_ID = A.TID)
WHERE C.CUM_ID = 'a001';

-------
commit
